// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhYhaCPzPGN_ihRAHWFrkeF8sv-4h52hM',
    appId: '1:159878223205:web:e8d2524c5fb1303afa7d8c',
    messagingSenderId: '227649431304',
    projectId: 'artisan-project-2a65a',
    authDomain: 'artisan-project-2a65a.firebaseapp.com',
    storageBucket: 'artisan-project-2a65a.firebasestorage.app',
    measurementId: 'G-WQ7T0PRGJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6TXjL6IDHRNZL73oANsnCESPekbsH5ZQ',
    appId: '1:227649431304:android:0f47dd82ea477bf3fd2ebd',
    messagingSenderId: '227649431304',
    projectId: 'artisan-project-2a65a',
    storageBucket: 'artisan-project-2a65a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa6ldy6q5ZLDqFZUqDNUmLhKhHbB3d6o0',
    appId: '1:159878223205:ios:827c9c57a3e59a44fa7d8c',
    messagingSenderId: '227649431304',
    projectId: 'artisan-project-2a65a',
    storageBucket: 'artisan-project-2a65a.firebasestorage.app',
    iosClientId:
        '159878223205-872nu2bq5vphf1d6oqv4qg6aje26bdvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.artisansProjectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa6ldy6q5ZLDqFZUqDNUmLhKhHbB3d6o0',
    appId: '1:159878223205:ios:827c9c57a3e59a44fa7d8c',
    messagingSenderId: '227649431304',
    projectId: 'artisan-project-2a65a',
    storageBucket: 'artisan-project-2a65a.firebasestorage.app',
    iosClientId:
        '159878223205-872nu2bq5vphf1d6oqv4qg6aje26bdvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.artisansProjectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhYhaCPzPGN_ihRAHWFrkeF8sv-4h52hM',
    appId: '1:159878223205:web:09805afa2f63c5a7fa7d8c',
    messagingSenderId: '227649431304',
    projectId: 'artisan-project-2a65a',
    authDomain: 'artisan-project-2a65a.firebaseapp.com',
    storageBucket: 'artisan-project-2a65a.firebasestorage.app',
    measurementId: 'G-LJ4ZGZF9C9',
  );
}
